version: "3.9"
services:
  xlights-seq:
    image: hislopkent/xlights-auto-seq:latest
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
      - ./generated:/app/generated
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --label-enable
    restart: unless-stopped
