version: "3.9"

services:
  xlights-seq:
    image: hislopkent/xlights-sequence-generator:latest
    container_name: xlights-seq
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./generated:/app/generated
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --label-enable
